ple# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mailBot.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from sendmail import Email


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(830, 615)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sendbutton = QtWidgets.QPushButton(self.centralwidget)
        self.sendbutton.setGeometry(QtCore.QRect(280, 310, 161, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.sendbutton.setFont(font)
        self.sendbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sendbutton.setAutoFillBackground(False)
        self.sendbutton.setFlat(False)
        self.sendbutton.setObjectName("sendbutton")
        self.subjectlineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.subjectlineEdit.setGeometry(QtCore.QRect(140, 180, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.subjectlineEdit.setFont(font)
        self.subjectlineEdit.setText("")
        self.subjectlineEdit.setObjectName("subjectlineEdit")
        self.subjectlabel = QtWidgets.QLabel(self.centralwidget)
        self.subjectlabel.setGeometry(QtCore.QRect(30, 190, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.subjectlabel.setFont(font)
        self.subjectlabel.setObjectName("subjectlabel")
        self.TitleLabel = QtWidgets.QLabel(self.centralwidget)
        self.TitleLabel.setGeometry(QtCore.QRect(260, 30, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.TitleLabel.setFont(font)
        self.TitleLabel.setObjectName("TitleLabel")
        self.sendtolabel = QtWidgets.QLabel(self.centralwidget)
        self.sendtolabel.setGeometry(QtCore.QRect(520, 140, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sendtolabel.setFont(font)
        self.sendtolabel.setObjectName("sendtolabel")
        self.clcheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.clcheckBox.setGeometry(QtCore.QRect(140, 240, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.clcheckBox.setFont(font)
        self.clcheckBox.setObjectName("clcheckBox")
        self.emailTotextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.emailTotextEdit.setGeometry(QtCore.QRect(520, 186, 271, 351))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.emailTotextEdit.setFont(font)
        self.emailTotextEdit.setObjectName("emailTotextEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 830, 26))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionVersion = QtWidgets.QAction(MainWindow)
        self.actionVersion.setObjectName("actionVersion")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuAbout.addAction(self.actionHelp)
        self.menuAbout.addAction(self.actionVersion)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.sendbutton.setText(_translate("MainWindow", "Send Mail"))
        self.subjectlabel.setText(_translate("MainWindow", "Subject"))
        self.TitleLabel.setText(_translate("MainWindow", "Email Assistance"))
        self.sendtolabel.setText(_translate("MainWindow", "Emial To:"))
        self.clcheckBox.setText(_translate("MainWindow", "Cover Letter"))
        self.emailTotextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                "p, li { white-space: pre-wrap; }\n"
                                                "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
                                                "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionVersion.setText(_translate("MainWindow", "Version"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

        self.sendbutton.clicked.connect(self.sendmail)

    # def buttonSet(self):
    #     self.sendbutton.clicked.connect(self.printfunc())

    def sendmail(self):

        mail_to = "example@gmail.com"

        email_obj = Email(mail_to)

        if mail_to:
            email_obj.send()
        else:
            print("mail id not found")


def printfunc(self):
    print("send button clicked!")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()

    sys.exit(app.exec_())
